"use client";

import { useEffect, useRef, type HTMLAttributes, type ReactNode } from "react";
import { Mesh, Program, Renderer, Triangle } from "ogl";

const MAX_POINTS = 64;
type BlendMode = "normal" | "screen" | "plus-lighter";
export interface GlowCursorProps extends Omit<HTMLAttributes<HTMLDivElement>, "color"> {
  color?: string; secondaryColor?: string; trailLength?: number; trailWidth?: number; trailTaper?: number; followSpeed?: number; glowIntensity?: number; glowSpread?: number; hotspot?: number; brightness?: number; opacity?: number; pulseSpeed?: number; noiseStrength?: number; idleFade?: boolean; idleTimeout?: number; fadeDuration?: number; blendMode?: BlendMode; maxDevicePixelRatio?: number; enabled?: boolean; children?: ReactNode;
}

const VERTEX = `attribute vec2 position; attribute vec2 uv; varying vec2 vUv; void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const FRAGMENT = `precision highp float;
#define MAX_POINTS 64
uniform vec2 uResolution,uPoints[MAX_POINTS]; uniform float uPointCount,uTrailWidth,uTaper,uGlowIntensity,uGlowSpread,uHotspot,uBrightness,uOpacity,uPulseSpeed,uNoiseStrength,uNormalBlend,uTime,uFade; uniform vec3 uColor,uSecondaryColor; varying vec2 vUv;
float srgb(float x){return x<=.00031308?12.92*x:1.055*pow(x,1./2.4)-.055;}
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}
void main(){vec2 px=vUv*uResolution;float den=max(uPointCount-1.,1.),strongest=0.,coreStrongest=0.,weight=0.;vec3 sum=vec3(0.);
for(int i=0;i<MAX_POINTS-1;i++){float index=float(i),active=1.-step(uPointCount-1.,index);vec2 start=uPoints[i],segment=uPoints[i+1]-start,toPixel=px-start;float along=clamp(dot(toPixel,segment)/max(dot(segment,segment),.0001),0.,1.),progress=clamp((index+along)/den,0.,1.),life=pow(max(1.-progress,0.),mix(.55,1.25,uTaper)),width=uTrailWidth*mix(1.,.25,pow(progress,mix(.55,1.6,uTaper))),dist=length(toPixel-segment*along),falloff=max(width*(.8+uGlowSpread*1.4),.5),beam=min(1.,(falloff*falloff)/(dist*dist+falloff*falloff)),core=exp(-pow(dist/max(width,.5),2.)*2.5),pulse=1.+sin(uTime*uPulseSpeed*3.-progress*11.)*.16*min(abs(uPulseSpeed),1.),intensity=(core+beam*uGlowIntensity*.55)*life*pulse*active;vec3 segmentColor=mix(uColor,uSecondaryColor,progress);strongest=max(strongest,intensity);coreStrongest=max(coreStrongest,core*life*active);sum+=segmentColor*intensity;weight+=intensity;}
float alpha=clamp(strongest*uOpacity*uFade,0.,1.);if(alpha<.0005)discard;vec3 color=sum/max(weight,.0001);color=mix(color,vec3(1.),smoothstep(.25,.95,coreStrongest)*uHotspot);float grain=(hash(floor(px)+vec2(floor(uTime*18.)*17.,floor(uTime*18.)*31.))*2.-1.)*((1.-exp(-uNoiseStrength*2.2))*.4);float light=srgb(clamp(strongest*uBrightness,0.,1.))*(1.+grain);vec3 normalColor=mix(color,vec3(1.),smoothstep(.45,1.,coreStrongest)*uHotspot*.35);gl_FragColor=vec4(mix(color*light,normalColor,uNormalBlend),mix(alpha,clamp(strongest*uBrightness*uOpacity*uFade,0.,1.),uNormalBlend));}`;

const rgb = (hex: string): [number, number, number] => { let value=(hex||"").replace("#","").trim(); if(value.length===3)value=value.split("").map((item)=>item+item).join("");const parsed=Number.parseInt(value||"000000",16);return [((parsed>>16)&255)/255,((parsed>>8)&255)/255,(parsed&255)/255]; };
const clamp = (value:number,min:number,max:number) => Math.min(Math.max(value,min),max);

export default function GlowCursor({ color="#67E8F9",secondaryColor="#A78BFA",trailLength=40,trailWidth=8,trailTaper=.8,followSpeed=.16,glowIntensity=1.9,glowSpread=1.2,hotspot=.65,brightness=1.25,opacity=1,pulseSpeed=1.1,noiseStrength=.035,idleFade=true,idleTimeout=700,fadeDuration=900,blendMode="screen",maxDevicePixelRatio=1.5,enabled=true,children,className="",style,...rest }: GlowCursorProps) {
  const containerRef=useRef<HTMLDivElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const propsRef=useRef({color,secondaryColor,trailLength,trailWidth,trailTaper,followSpeed,glowIntensity,glowSpread,hotspot,brightness,opacity,pulseSpeed,noiseStrength,idleFade,idleTimeout,fadeDuration,blendMode,maxDevicePixelRatio,enabled});
  propsRef.current={color,secondaryColor,trailLength,trailWidth,trailTaper,followSpeed,glowIntensity,glowSpread,hotspot,brightness,opacity,pulseSpeed,noiseStrength,idleFade,idleTimeout,fadeDuration,blendMode,maxDevicePixelRatio,enabled};
  useEffect(()=>{const container=containerRef.current,canvas=canvasRef.current;if(!container||!canvas||window.matchMedia("(pointer: coarse)").matches)return;const renderer=new Renderer({canvas,alpha:true,dpr:Math.min(devicePixelRatio||1,maxDevicePixelRatio)}),gl=renderer.gl;gl.clearColor(0,0,0,0);const data=Array(MAX_POINTS*2).fill(0),points=Array.from({length:MAX_POINTS},()=>({x:0,y:0})),target={x:0,y:0},head={x:0,y:0};const program=new Program(gl,{vertex:VERTEX,fragment:FRAGMENT,uniforms:{uResolution:{value:[1,1]},uPoints:{value:data},uPointCount:{value:trailLength},uColor:{value:rgb(color)},uSecondaryColor:{value:rgb(secondaryColor)},uTrailWidth:{value:trailWidth},uTaper:{value:trailTaper},uGlowIntensity:{value:glowIntensity},uGlowSpread:{value:glowSpread},uHotspot:{value:hotspot},uBrightness:{value:brightness},uOpacity:{value:opacity},uPulseSpeed:{value:pulseSpeed},uNoiseStrength:{value:noiseStrength},uNormalBlend:{value:blendMode==="normal"?1:0},uTime:{value:0},uFade:{value:0}},transparent:true,depthTest:false,depthWrite:false});const mesh=new Mesh(gl,{geometry:new Triangle(gl),program});let initialized=false,inside=false,fade=0,lastInput=performance.now(),lastFrame=performance.now(),frame=0,destroyed=false;
    const resize=()=>{const width=Math.max(container.clientWidth,1),height=Math.max(container.clientHeight,1);renderer.setSize(width,height);program.uniforms.uResolution.value=[width,height];};
    const move=(event:PointerEvent)=>{const rect=container.getBoundingClientRect(),x=clamp(event.clientX-rect.left,0,rect.width),y=clamp(rect.height-(event.clientY-rect.top),0,rect.height);if(!initialized){target.x=head.x=x;target.y=head.y=y;points.forEach((point)=>{point.x=x;point.y=y;});initialized=true;fade=1;}target.x=x;target.y=y;inside=true;lastInput=performance.now();};
    const leave=()=>{inside=false;lastInput=performance.now();};
    const render=(now:number)=>{if(destroyed)return;const config=propsRef.current,delta=Math.min((now-lastFrame)/16.667,3);lastFrame=now;if(initialized){const headEase=1-Math.pow(1-clamp(config.followSpeed,.01,.99),delta),chainBase=clamp(.28+config.followSpeed*.35,.08,.92),chainEase=1-Math.pow(1-chainBase,delta);head.x+=(target.x-head.x)*headEase;head.y+=(target.y-head.y)*headEase;points[0].x=head.x;points[0].y=head.y;for(let index=1;index<MAX_POINTS;index+=1){points[index].x+=(points[index-1].x-points[index].x)*chainEase;points[index].y+=(points[index-1].y-points[index].y)*chainEase;}points.forEach((point,index)=>{data[index*2]=point.x;data[index*2+1]=point.y;});}const shouldFade=config.idleFade&&(!inside||now-lastInput>config.idleTimeout);fade+=((initialized&&config.enabled&&!shouldFade?1:0)-fade)*Math.min(1,(16.667*delta/Math.max(config.fadeDuration,16))*7);program.uniforms.uPointCount.value=clamp(Math.round(config.trailLength),2,MAX_POINTS);program.uniforms.uColor.value=rgb(config.color);program.uniforms.uSecondaryColor.value=rgb(config.secondaryColor);program.uniforms.uTrailWidth.value=Math.max(config.trailWidth,.1);program.uniforms.uTaper.value=clamp(config.trailTaper,0,1);program.uniforms.uGlowIntensity.value=Math.max(config.glowIntensity,0);program.uniforms.uGlowSpread.value=Math.max(config.glowSpread,0);program.uniforms.uHotspot.value=clamp(config.hotspot,0,1);program.uniforms.uBrightness.value=Math.max(config.brightness,0);program.uniforms.uOpacity.value=clamp(config.opacity,0,1);program.uniforms.uPulseSpeed.value=config.pulseSpeed;program.uniforms.uNoiseStrength.value=clamp(config.noiseStrength,0,1);program.uniforms.uNormalBlend.value=config.blendMode==="normal"?1:0;program.uniforms.uTime.value=now*.001;program.uniforms.uFade.value=fade;renderer.render({scene:mesh});frame=requestAnimationFrame(render);};
    const observer=new ResizeObserver(resize);observer.observe(container);container.addEventListener("pointermove",move);container.addEventListener("pointerenter",move);container.addEventListener("pointerleave",leave);resize();frame=requestAnimationFrame(render);return()=>{destroyed=true;cancelAnimationFrame(frame);observer.disconnect();container.removeEventListener("pointermove",move);container.removeEventListener("pointerenter",move);container.removeEventListener("pointerleave",leave);mesh.geometry.remove();program.remove();};
  },[maxDevicePixelRatio]);
  return <div ref={containerRef} className={`glow-cursor${className?` ${className}`:""}`} style={style} {...rest}><canvas ref={canvasRef} className="glow-cursor__canvas" style={{mixBlendMode:blendMode}} aria-hidden="true" />{children&&<div className="glow-cursor__content">{children}</div>}</div>;
}
